<?php
return [ 
    'CURRENCY_LIST'=>[
        ["code"=>"ALL", "symbol"=>"", "country"=>"Albania Lek"],
        ["code"=>"AFN", "symbol"=>"", "country"=>"Afghanistan Afghani"],
        ["code"=>"ARS", "symbol"=>"", "country"=>"Argentina Peso"],
        ["code"=>"AWG", "symbol"=>"", "country"=>"Aruba Guilder"],
        ["code"=>"AUD", "symbol"=>"$", "country"=>"Australia Dollar"],
        ["code"=>"AZN", "symbol"=>"", "country"=>"Azerbaijan New Manat"],
        ["code"=>"BSD", "symbol"=>"", "country"=>"Bahamas Dollar"],
        ["code"=>"BBD", "symbol"=>"", "country"=>"Barbados Dollar"],
        ["code"=>"BDT", "symbol"=>"", "country"=>"Bangladeshi taka"],
        ["code"=>"BYR", "symbol"=>"", "country"=>"Belarus Ruble"],
        ["code"=>"BZD", "symbol"=>"", "country"=>"Belize Dollar"],
        ["code"=>"BMD", "symbol"=>"", "country"=>"Bermuda Dollar"],
        ["code"=>"BOB", "symbol"=>"", "country"=>"Bolivia Boliviano"],
        ["code"=>"BAM", "symbol"=>"", "country"=>"Bosnia and Herzegovina Convertible Marka"],
        ["code"=>"BWP", "symbol"=>"", "country"=>"Botswana Pula"],
        ["code"=>"BGN", "symbol"=>"", "country"=>"Bulgaria Lev"],
        ["code"=>"BRL", "symbol"=>"R$", "country"=>"Brazil Real"],
        ["code"=>"BND", "symbol"=>"", "country"=>"Brunei Darussalam Dollar"],
        ["code"=>"KHR", "symbol"=>"", "country"=>"Cambodia Riel"],
        ["code"=>"CAD", "symbol"=>"C$", "country"=>"Canada Dollar"],
        ["code"=>"KYD", "symbol"=>"", "country"=>"Cayman Islands Dollar"],
        ["code"=>"CLP", "symbol"=>"", "country"=>"Chile Peso"],
        ["code"=>"CNY", "symbol"=>"", "country"=>"China Yuan Renminbi"],
        ["code"=>"COP", "symbol"=>"", "country"=>"Colombia Peso"],
        ["code"=>"CRC", "symbol"=>"", "country"=>"Costa Rica Colon"],
        ["code"=>"HRK", "symbol"=>"", "country"=>"Croatia Kuna"],
        ["code"=>"CUP", "symbol"=>"", "country"=>"Cuba Peso"],
        ["code"=>"CZK", "symbol"=>"Kč", "country"=>"Czech Republic Koruna"],
        ["code"=>"DKK", "symbol"=>"kr", "country"=>"Denmark Krone"],
        ["code"=>"DOP", "symbol"=>"", "country"=>"Dominican Republic Peso"],
        ["code"=>"XCD", "symbol"=>"", "country"=>"East Caribbean Dollar"],
        ["code"=>"EGP", "symbol"=>"", "country"=>"Egypt Pound"],
        ["code"=>"SVC", "symbol"=>"", "country"=>"El Salvador Colon"],
        ["code"=>"EUR", "symbol"=>"€", "country"=>"Euro Member Countries"],
        ["code"=>"FKP", "symbol"=>"", "country"=>"Falkland Islands (Malvinas) Pound"],
        ["code"=>"FJD", "symbol"=>"", "country"=>"Fiji Dollar"],
        ["code"=>"GHC", "symbol"=>"", "country"=>"Ghana Cedis"],
        ["code"=>"GIP", "symbol"=>"", "country"=>"Gibraltar Pound"],
        ["code"=>"GTQ", "symbol"=>"", "country"=>"Guatemala Quetzal"],
        ["code"=>"GGP", "symbol"=>"", "country"=>"Guernsey Pound"],
        ["code"=>"GYD", "symbol"=>"", "country"=>"Guyana Dollar"],
        ["code"=>"HNL", "symbol"=>"", "country"=>"Honduras Lempira"],
        ["code"=>"HKD", "symbol"=>"", "country"=>"Hong Kong Dollar"],
        ["code"=>"HUF", "symbol"=>"Ft", "country"=>"Hungary Forint"],
        ["code"=>"ISK", "symbol"=>"", "country"=>"Iceland Krona"],
        ["code"=>"INR", "symbol"=>"₹", "country"=>"India Rupee"],
        ["code"=>"IDR", "symbol"=>"", "country"=>"Indonesia Rupiah"],
        ["code"=>"IRR", "symbol"=>"", "country"=>"Iran Rial"],
        ["code"=>"IMP", "symbol"=>"", "country"=>"Isle of Man Pound"],
        ["code"=>"ILS", "symbol"=>"₪", "country"=>"Israel Shekel"],
        ["code"=>"JMD", "symbol"=>"", "country"=>"Jamaica Dollar"],
        ["code"=>"JPY", "symbol"=>"¥", "country"=>"Japan Yen"],
        ["code"=>"JEP", "symbol"=>"", "country"=>"Jersey Pound"],
        ["code"=>"KZT", "symbol"=>"", "country"=>"Kazakhstan Tenge"],
        ["code"=>"KPW", "symbol"=>"", "country"=>"Korea (North) Won"],
        ["code"=>"KRW", "symbol"=>"", "country"=>"Korea (South) Won"],
        ["code"=>"KGS", "symbol"=>"", "country"=>"Kyrgyzstan Som"],
        ["code"=>"LAK", "symbol"=>"", "country"=>"Laos Kip"],
        ["code"=>"LRD", "symbol"=>"", "country"=>"Lebanon Pound"],
        ["code"=>"LRD", "symbol"=>"", "country"=>"Liberia Dollar"],
        ["code"=>"MKD", "symbol"=>"", "country"=>"Macedonia Denar"],
        ["code"=>"MYR", "symbol"=>"RM", "country"=>"Malaysia Ringgit"],
        ["code"=>"MUR", "symbol"=>"", "country"=>"Mauritius Rupee"],
        ["code"=>"MXN", "symbol"=>"", "country"=>"Mexico Peso"],
        ["code"=>"MNT", "symbol"=>"", "country"=>"Mongolia Tughrik"],
        ["code"=>"MZN", "symbol"=>"", "country"=>"Mozambique Metical"],
        ["code"=>"NAD", "symbol"=>"", "country"=>"Namibia Dollar"],
        ["code"=>"NPR", "symbol"=>"", "country"=>"Nepal Rupee"],
        ["code"=>"ANG", "symbol"=>"", "country"=>"Netherlands Antilles Guilder"],
        ["code"=>"NZD", "symbol"=>"", "country"=>"New Zealand Dollar"],
        ["code"=>"NIO", "symbol"=>"", "country"=>"Nicaragua Cordoba"],
        ["code"=>"NGN", "symbol"=>"", "country"=>"Nigeria Naira"],
        ["code"=>"NOK", "symbol"=>"kr", "country"=>"Norway Krone"],
        ["code"=>"OMR", "symbol"=>"", "country"=>"Oman Rial"],
        ["code"=>"PKR", "symbol"=>"", "country"=>"Pakistan Rupee"],
        ["code"=>"PAB", "symbol"=>"", "country"=>"Panama Balboa"],
        ["code"=>"PGK", "symbol"=>"k", "country"=>"Papua New Guinean"],
        ["code"=>"PYG", "symbol"=>"", "country"=>"Paraguay Guarani"],
        ["code"=>"PEN", "symbol"=>"", "country"=>"Peru Nuevo Sol"],
        ["code"=>"PHP", "symbol"=>"₱", "country"=>"Philippines Peso"],
        ["code"=>"PLN", "symbol"=>"zł", "country"=>"Poland Zloty"],
        ["code"=>"QAR", "symbol"=>"", "country"=>"Qatar Riyal"],
        ["code"=>"RON", "symbol"=>"", "country"=>"Romania New Leu"],
        ["code"=>"RUB", "symbol"=>"", "country"=>"Russia Ruble"],
        ["code"=>"SHP", "symbol"=>"", "country"=>"Saint Helena Pound"],
        ["code"=>"SAR", "symbol"=>"", "country"=>"Saudi Arabia Riyal"],
        ["code"=>"RSD", "symbol"=>"", "country"=>"Serbia Dinar"],
        ["code"=>"SCR", "symbol"=>"", "country"=>"Seychelles Rupee"],
        ["code"=>"SGD", "symbol"=>"", "country"=>"Singapore Dollar"],
        ["code"=>"SBD", "symbol"=>"", "country"=>"Solomon Islands Dollar"],
        ["code"=>"SOS", "symbol"=>"", "country"=>"Somalia Shilling"],
        ["code"=>"ZAR", "symbol"=>"", "country"=>"South Africa Rand"],
        ["code"=>"LKR", "symbol"=>"", "country"=>"Sri Lanka Rupee"],
        ["code"=>"SEK", "symbol"=>"kr", "country"=>"Sweden Krona"],
        ["code"=>"CHF", "symbol"=>"Fr", "country"=>"Switzerland Franc"],
        ["code"=>"SRD", "symbol"=>"", "country"=>"Suriname Dollar"],
        ["code"=>"SYP", "symbol"=>"", "country"=>"Syria Pound"],
        ["code"=>"TWD", "symbol"=>"$", "country"=>"Taiwan New Dollar"],
        ["code"=>"THB", "symbol"=>"฿", "country"=>"Thailand Baht"],
        ["code"=>"TTD", "symbol"=>"", "country"=>"Trinidad and Tobago Dollar"],
        ["code"=>"TRY", "symbol"=>"₺", "country"=>"Turkey Lira"],
        ["code"=>"TRL", "symbol"=>"", "country"=>"Turkey Lira"],
        ["code"=>"TVD", "symbol"=>"", "country"=>"Tuvalu Dollar"],
        ["code"=>"UAH", "symbol"=>"", "country"=>"Ukraine Hryvna"],
        ["code"=>"GBP", "symbol"=>"£", "country"=>"United Kingdom Pound"],
        ["code"=>"UGX", "symbol"=>"", "country"=>"Uganda Shilling"],
        ["code"=>"USD", "symbol"=>"$", "country"=>"United States Dollar"],
        ["code"=>"UYU", "symbol"=>"", "country"=>"Uruguay Peso"],
        ["code"=>"UZS", "symbol"=>"", "country"=>"Uzbekistan Som"],
        ["code"=>"VEF", "symbol"=>"", "country"=>"Venezuela Bolivar"],
        ["code"=>"VND", "symbol"=>"", "country"=>"Viet Nam Dong"],
        ["code"=>"YER", "symbol"=>"", "country"=>"Yemen Rial"],
        ["code"=>"ZWD", "symbol"=>"", "country"=>"Zimbabwe Dollar"]
      ],
];


